### ISSUE TITLE
Store Invites

### ISSUE THREAD

**Issue by FeelsBadMan1** [DiscordFederation/DisboardScraper#1]
Hello, the script works fine, However it would be nice if it store the guild invitelinks too. Otherwise its not really useful for me maybe store them in a extrafile or in the csv file in a extra row too.

**Comment by daegontaven** [comment]
@FeelsBadMan1 This is something I already had developed. Do want the actual invite links or just the disboard links that redirect to the actual invite links? I feel the latter may be more useful since the former links expire since it's generated by disboard's bot.

**Comment by FeelsBadMan1** [comment]
I made a other script that only stores invites. However they ratelimit you and then you need custom headers. I tried lot of stuff but nothing helped me; I tried to store the headers in a extra Textdocument, get a ranom header and use it. Somehow Python add useless characters to the header that make the header invalid so the script throw a error. Probably you could help me with this:
```
    def get_soup(url, header):
        time.sleep(random.choice([1, 2, 3]))
        return BeautifulSoup(urlopen(Request(url, headers=header)), "html.parser")
```
```
        with open("useragents.txt", "r") as user_agents_file:
            user_agents_lines = user_agents_file.readlines()
            print(user_agents_lines)
            # count
            user_agent = random.choice(user_agents_lines)
            print(f"USER-AGENT: {user_agent}")
            # for user_agent in user_agents_lines:
            #     count += 1
            #     print(f"Line{count}: {user_agent.strip()}")
```
```
Traceback (most recent call last):
  File "D:\my_python_projects\Disboard scraper\disboard invitescraper\main.py", line 111, in <module>
    scraper() # run the function
  File "D:\my_python_projects\Disboard scraper\disboard invitescraper\main.py", line 62, in scraper
    soup = get_soup(surveyingurl, disboardheader)
  File "D:\my_python_projects\Disboard scraper\disboard invitescraper\main.py", line 43, in get_soup
    return BeautifulSoup(urlopen(Request(url, headers=header)), "html.parser")
  File "D:\Downloads\Python\python 3.9.6\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Downloads\Python\python 3.9.6\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "D:\Downloads\Python\python 3.9.6\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\Downloads\Python\python 3.9.6\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\Downloads\Python\python 3.9.6\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\Downloads\Python\python 3.9.6\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\Downloads\Python\python 3.9.6\lib\http\client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Downloads\Python\python 3.9.6\lib\http\client.py", line 1298, in _send_request
    self.putheader(hdr, value)
  File "D:\Downloads\Python\python 3.9.6\lib\http\client.py", line 1235, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36\n'
```

**Comment by FeelsBadMan1** [comment]
> 
> 
> @FeelsBadMan1 This is something I already had developed. Do want the actual invite links or just the disboard links that redirect to the actual invite links? I feel the latter may be more useful since the former links expire since it's generated by disboard's bot.

I think the disboardlinks would be more useful then ;D

**Comment by daegontaven** [comment]
@FeelsBadMan1 the latest version of the code stores disboard links in a column in csv

**Comment by FeelsBadMan1** [comment]
> 
> 
> @FeelsBadMan1 the latest version of the code stores disboard links in a column in csv

Okay thank u. However i implemented something into my code but now i want to know, how to only get the name printed and how i can avid writing duplicated servers (same server with same membercount etc. is written into the file with different invites each time)
![grafik](https://user-images.githubusercontent.com/40109798/130366255-a1699f34-78ab-4d02-8ec2-f491d113c42a.png)

**Comment by FeelsBadMan1** [comment]
still no  answer after 22 days....

**Comment by daegontaven** [comment]
> still no answer after 22 days....

Sorry, but I will not be adding this feature (at least not soon anyways). I already have my plate full right now. Feel free to create a PR though.
